# ~/.tmux.conf

# Fix colors inside Ghostty terminal
set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# Enable mouse support for resizing panes and scrolling
set -g mouse on

# Set default shell to Zsh
set -g default-shell /usr/bin/zsh

# Gruvbox styling for the bottom status bar
set -g status-style bg="#32302f",fg="#ebdbb2"
set -g window-status-current-style bg="#fe8019",fg="#282828",bold
